version: 0.0.5
setup:
  structure:
    - data:
      - data_conf:
      - winequality-red.csv
    - src:
      - data_analysis:
      - ml_pipelines:
      - ml_primitives:
    - Pipfile
    - Pipfile.lock
  processes:
    - project_initializer
watchdog:
  - directory: data
    events:
      on_create:
        - add_to_DVC
        - generate_profile
commands:
  - command_name: print_message
  - command_name: scaffold_EDA
  - command_name: inspect_data
    settings:
      ignore_unknown_options: True
      allow_extra_args: True