name: default-env #Name has to be the same as the file name in the qml assets folder (name will later be changed here)
version: 0.0.5
setup:
  structure:
    - data:
      - data_conf:
      - winequality-red.csv # TODO This is being added to DVC Hardcoded
    - src:
      - ml_pipelines:
      - ml_primitives:
    - Pipfile
    - Pipfile.lock
  processes:
    - project_initializer
watchdog:
  - directory: data
    events:
      on_create:
        - add_to_DVC
        - generate_profile
      on_delete:
        - yey
  - directory: banana
    events:
      on_modify:
        - eat
commands:
  - print-message