name: default-env
version: 0.0.4
setup:
  structure:
    - data:
      - data_conf:
      - winequality-red.csv # TODO This is being added to DVC Hardcoded
    - src:
      - ml_pipelines:
      - ml_primitives:
    - Pipfile
    - Pipfile.lock
  run:
    - project_initializer
watchdog:
  - data:
    - on_create:
        - add_to_DVC
        - generate_profile
commands:
  - inspect-data
  - stuff