version: 0.2.0
setup:
  structure:
    - data:
      - data_conf:
    - src:
      - data_analysis:
        - dataset_generators:
      - ml_pipelines:
        - pipeline_annonations:
      - mlblocks_primitives:
    - Pipfile
    - Pipfile.lock
  processes:
    - project_initializer
watchdog:
  - directory: data
    events:
      on_create:
        - add_to_DVC
        - generate_profile
      on_modified:
        - generate_profile
      on_any_event:
        - print_event
commands:
  - command_name: print_message
  - command_name: scaffold_EDA
  - command_name: gen_dataset
  - command_name: scaffold_ml_pipeline
  - command_name: inspect_data
    settings:
      ignore_unknown_options: True
      allow_extra_args: True